port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
  - name: "Node_01"
    type: hysteria
    server: 89.144.35.30
    port: 23008
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_02"
    type: hysteria
    server: 5.178.101.33
    port: 23008
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_03"
    type: vless
    server: 195.154.200.13
    port: 17401
    uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
    udp: true
    network: tcp
    tls: true
    reality-opts:
      public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
      short-id: 8ef4455ba637425b
    client-fingerprint: chrome
  - name: "Node_04"
    type: hysteria
    server: 2001:bc8:32d7:402::3
    port: 20001
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_05"
    type: hysteria
    server: 2001:bc8:32d7:402::4
    port: 20001
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_06"
    type: anytls
    server: 45.221.98.14
    port: 59901
    password: dongtaiwang.com
    skip-cert-verify: true
    udp: true
  - name: "Node_07"
    type: vless
    server: 2001:bc8:32d7:181::2
    port: 17401
    uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
    udp: true
    network: tcp
    tls: true
    reality-opts:
      public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
      short-id: 8ef4455ba637425b
    client-fingerprint: chrome
  - name: "Node_08"
    type: vless
    server: 2001:bc8:32d7:181::3
    port: 17401
    uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
    udp: true
    network: tcp
    tls: true
    reality-opts:
      public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
      short-id: 8ef4455ba637425b
    client-fingerprint: chrome
  - name: "Node_09"
    type: mieru
    server: 157.254.223.48
    port: 33990
    password: dongtaiwang.com
    transport: TCP
  - name: "Node_10"
    type: tuic
    server: 89.144.35.231
    port: 33457
    uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
    password: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    username: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
    congestion-controller: bbr
    reduce-rtt: true
  - name: "Node_11"
    type: tuic
    server: 2a14:7583:299d::a
    port: 33457
    uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
    password: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    username: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
    congestion-controller: bbr
    reduce-rtt: true
  - name: "Node_12"
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn: [h3]
    up: "11 Mbps"
    down: "55 Mbps"

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - "Node_01"
      - "Node_02"
      - "Node_03"
      - "Node_04"
      - "Node_05"
      - "Node_06"
      - "Node_07"
      - "Node_08"
      - "Node_09"
      - "Node_10"
      - "Node_11"
      - "Node_12"
      - DIRECT

rules:
  # æ ¸å¿ƒæœåŠ¡åˆ†æµ
  - DOMAIN-SUFFIX,google.com,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-KEYWORD,github,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-KEYWORD,youtube,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-KEYWORD,google,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-SUFFIX,telegram.org,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  
  # å›½å†…å¸¸ç”¨æœåŠ¡ç›´è¿ (ç¥æœºè§„åˆ™ç²¾ç®€ç‰ˆ)
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-KEYWORD,taobao,DIRECT
  - DOMAIN-KEYWORD,jd,DIRECT
  - DOMAIN-KEYWORD,aliyun,DIRECT
  - DOMAIN-KEYWORD,tencent,DIRECT
  
  # å±€åŸŸç½‘ä¸åœ°ç†ä½ç½®
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  
  # å…œåº•è§„åˆ™
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©