ipv6: true
proxies:
- name: ğŸŒ[VLESS] 02 (01-10 17:33)
  server: 195.154.200.13
  port: 17401
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
- name: ğŸŒ[VLESS] 03 (01-10 17:33)
  server: 2001:bc8:32d7:181::2
  port: 17401
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
- name: ğŸŒ[VLESS] 04 (01-10 17:33)
  server: 2001:bc8:32d7:181::3
  port: 17401
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
- name: ğŸŒ[VLESS] 05 (01-10 17:33)
  server: 157.254.223.48
  port: 33990
  type: vless
  uuid: dongtaiwang.com
  tls: true
  servername: apple.com
  network: tcp
  udp: true
- name: ğŸŒ[TUIC] 06 (01-10 17:33)
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: dongtaiwang.com
  sni: apple.com
  alpn:
  - h3
- name: ğŸŒ[TUIC] 07 (01-10 17:33)
  server: 2a14:7583:299d::a
  port: 33457
  type: tuic
  uuid: dongtaiwang.com
  sni: apple.com
  alpn:
  - h3
- name: ğŸŒ[VLESS] 08 (01-10 17:33)
  server: 157.254.223.44
  port: 18959
  type: vless
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
    short-id: d557c6895d014075
- name: ğŸŒ[VLESS] 09 (01-10 17:33)
  server: 89.144.35.232
  port: 15531
  type: vless
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
    short-id: 8346964417a2552b
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
  - ğŸŒ[VLESS] 02 (01-10 17:33)
  - ğŸŒ[VLESS] 03 (01-10 17:33)
  - ğŸŒ[VLESS] 04 (01-10 17:33)
  - ğŸŒ[VLESS] 05 (01-10 17:33)
  - ğŸŒ[TUIC] 06 (01-10 17:33)
  - ğŸŒ[TUIC] 07 (01-10 17:33)
  - ğŸŒ[VLESS] 08 (01-10 17:33)
  - ğŸŒ[VLESS] 09 (01-10 17:33)
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - ğŸŒ[VLESS] 02 (01-10 17:33)
  - ğŸŒ[VLESS] 03 (01-10 17:33)
  - ğŸŒ[VLESS] 04 (01-10 17:33)
  - ğŸŒ[VLESS] 05 (01-10 17:33)
  - ğŸŒ[TUIC] 06 (01-10 17:33)
  - ğŸŒ[TUIC] 07 (01-10 17:33)
  - ğŸŒ[VLESS] 08 (01-10 17:33)
  - ğŸŒ[VLESS] 09 (01-10 17:33)
rules:
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
