proxies:
  # - name: dongtaiwang.com_1     ... (需要转换)
  # - name: dongtaiwang.com_4     ... (需要转换)
  # - name: dongtaiwang.com_0     ... (需要转换)
  # - name: dongtaiwang.com_2     ... (需要转换)
  # - name: dongtaiwang.com_3     ... (需要转换)
  # - name: dongtaiwang.com_2     ... (需要转换)
  # - name: dongtaiwang.com_1     ... (需要转换)
  # - name: dongtaiwang.com_0     ... (需要转换)
