proxies:
- cipher: auto
  name: ğŸŒ_01_01-10 21:54
  network: tcp
  port: 17401
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  server: 195.154.200.13
  skip-cert-verify: true
  sni: itunes.apple.com
  tls: true
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
- cipher: auto
  name: ğŸŒ_02_01-10 21:54
  network: tcp
  port: 59901
  server: 45.221.98.14
  skip-cert-verify: true
  tls: true
  type: vless
  uuid: dongtaiwang.com
- cipher: auto
  name: ğŸŒ_03_01-10 21:54
  network: tcp
  port: 2
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  server: '2001:bc8:32d7:181:'
  skip-cert-verify: true
  sni: itunes.apple.com
  tls: true
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
- cipher: auto
  name: ğŸŒ_04_01-10 21:54
  network: tcp
  port: 3
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  server: '2001:bc8:32d7:181:'
  skip-cert-verify: true
  sni: itunes.apple.com
  tls: true
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
- cipher: auto
  name: ğŸŒ_05_01-10 21:54
  network: tcp
  port: 33990
  server: 157.254.223.48
  skip-cert-verify: true
  tls: false
  type: vless
  uuid: dongtaiwang.com
- cipher: auto
  name: ğŸŒ_06_01-10 21:54
  network: tcp
  port: 33457
  server: 89.144.35.231
  skip-cert-verify: true
  sni: apple.com
  tls: true
  type: vless
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
- cipher: auto
  name: ğŸŒ_07_01-10 21:54
  network: tcp
  port: 443
  server: 2a14
  skip-cert-verify: true
  sni: apple.com
  tls: true
  type: vless
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
- cipher: auto
  name: ğŸŒ_08_01-10 21:54
  network: tcp
  port: 443
  server: 157.254.223.43
  skip-cert-verify: true
  sni: apple.com
  tls: true
  type: vless
  uuid: dongtaiwang.com
- cipher: auto
  name: ğŸŒ_09_01-10 21:54
  network: tcp
  port: 22000
  server: 62.210.124.146
  skip-cert-verify: true
  sni: www.microsoft.com
  tls: true
  type: vless
  uuid: dongtaiwang.com
- cipher: auto
  name: ğŸŒ_10_01-10 21:54
  network: tcp
  port: 50022
  server: 2a14:7584:d04a::a
  skip-cert-verify: true
  sni: apple.com
  tls: true
  type: vless
  uuid: dongtaiwang.com
- cipher: auto
  name: ğŸŒ_11_01-10 21:54
  network: tcp
  port: 18959
  server: 157.254.223.44
  skip-cert-verify: true
  tls: false
  type: vless
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
- cipher: auto
  name: ğŸŒ_12_01-10 21:54
  network: tcp
  port: 15531
  server: 89.144.35.232
  skip-cert-verify: true
  tls: false
  type: vless
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  proxies:
  - DIRECT
  - ğŸŒ_01_01-10 21:54
  - ğŸŒ_02_01-10 21:54
  - ğŸŒ_03_01-10 21:54
  - ğŸŒ_04_01-10 21:54
  - ğŸŒ_05_01-10 21:54
  - ğŸŒ_06_01-10 21:54
  - ğŸŒ_07_01-10 21:54
  - ğŸŒ_08_01-10 21:54
  - ğŸŒ_09_01-10 21:54
  - ğŸŒ_10_01-10 21:54
  - ğŸŒ_11_01-10 21:54
  - ğŸŒ_12_01-10 21:54
  type: select
rules:
- MATCH,èŠ‚ç‚¹é€‰æ‹©
