ipv6: true
allow-lan: true
mode: rule
proxies:
- name: https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  type: hysteria
  server: 89.144.35.30
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: dongtaiwang.com_1_01-10 20:24
  type: hysteria
  server: 5.178.101.33
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: dongtaiwang.com_2_01-10 20:24
  type: vless
  server: 195.154.200.13
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: dongtaiwang.com_3_01-10 20:24
  type: hysteria
  server: 2001:bc8:32d7:402::3
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: dongtaiwang.com_4_01-10 20:24
  type: hysteria
  server: 2001:bc8:32d7:402::4
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: dongtaiwang.com_0_01-10 20:24
  type: anytls
  server: 45.221.98.14
  port: 59901
  password: dongtaiwang.com
  client-fingerprint: chrome
  udp: true
  idle-session-check-interval: 30
  idle-session-timeout: 30
  min-idle-session: 0
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: dongtaiwang.com_1_01-10 20:24
  type: vless
  server: 2001:bc8:32d7:181::2
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: dongtaiwang.com_2_01-10 20:24
  type: vless
  server: 2001:bc8:32d7:181::3
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: dongtaiwang.com_0_01-10 20:24
  type: mieru
  server: 157.254.223.48
  port: 33990
  transport: TCP
  username: dongtaiwang.com
  password: dongtaiwang.com
- name: https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: dongtaiwang.com_1_01-10 20:24
  server: 2a14:7583:299d::a
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  type: hysteria
  server: 2a14:7584:d097::a
  port: 54177
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- type: vless
  tag: https://github.com/Alvin9999-newpac/fanqiang/wiki
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  packet_encoding: xudp
  server: 157.254.223.44
  server_port: 18959
  flow: ''
  tls:
    enabled: true
    server_name: itunes.apple.com
    utls:
      enabled: true
      fingerprint: chrome
    reality:
      enabled: true
      public_key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
      short_id: d557c6895d014075
  multiplex:
    enabled: true
    protocol: h2mux
    max_connections: 1
    min_streams: 4
    padding: true
    brutal:
      enabled: true
      up_mbps: 50
      down_mbps: 100
  name: node_01-10 20:24
- type: vless
  tag: https://github.com/Alvin9999-newpac/fanqiang/wiki
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  packet_encoding: xudp
  server: 89.144.35.232
  server_port: 15531
  flow: ''
  tls:
    enabled: true
    server_name: itunes.apple.com
    utls:
      enabled: true
      fingerprint: chrome
    reality:
      enabled: true
      public_key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
      short_id: 8346964417a2552b
  multiplex:
    enabled: true
    protocol: h2mux
    max_connections: 1
    min_streams: 4
    padding: true
    brutal:
      enabled: true
      up_mbps: 50
      down_mbps: 100
  name: node_01-10 20:24
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - DIRECT
  - https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  - dongtaiwang.com_1_01-10 20:24
  - dongtaiwang.com_2_01-10 20:24
  - dongtaiwang.com_3_01-10 20:24
  - dongtaiwang.com_4_01-10 20:24
  - dongtaiwang.com_0_01-10 20:24
  - dongtaiwang.com_1_01-10 20:24
  - dongtaiwang.com_2_01-10 20:24
  - dongtaiwang.com_0_01-10 20:24
  - https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  - dongtaiwang.com_1_01-10 20:24
  - https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  - node_01-10 20:24
  - node_01-10 20:24
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  - dongtaiwang.com_1_01-10 20:24
  - dongtaiwang.com_2_01-10 20:24
  - dongtaiwang.com_3_01-10 20:24
  - dongtaiwang.com_4_01-10 20:24
  - dongtaiwang.com_0_01-10 20:24
  - dongtaiwang.com_1_01-10 20:24
  - dongtaiwang.com_2_01-10 20:24
  - dongtaiwang.com_0_01-10 20:24
  - https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  - dongtaiwang.com_1_01-10 20:24
  - https://github.com/Alvin9999-newpac/fanqiang/wiki_01-10 20:24
  - node_01-10 20:24
  - node_01-10 20:24
rules:
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
