ipv6: true
allow-lan: true
proxies:
- name: Node_1_01-10 20:45
  type: hysteria
  server: 89.144.35.30
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: Node_2_01-10 20:45
  type: hysteria
  server: 5.178.101.33
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: Node_3_01-10 20:45
  type: vless
  server: 195.154.200.13
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: Node_4_01-10 20:45
  type: hysteria
  server: 2001:bc8:32d7:402::3
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: Node_5_01-10 20:45
  type: hysteria
  server: 2001:bc8:32d7:402::4
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: Node_6_01-10 20:45
  type: anytls
  server: 45.221.98.14
  port: 59901
  password: dongtaiwang.com
  client-fingerprint: chrome
  udp: true
  idle-session-check-interval: 30
  idle-session-timeout: 30
  min-idle-session: 0
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: Node_7_01-10 20:45
  type: vless
  server: 2001:bc8:32d7:181::2
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: Node_8_01-10 20:45
  type: vless
  server: 2001:bc8:32d7:181::3
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: Node_9_01-10 20:45
  type: mieru
  server: 157.254.223.48
  port: 33990
  transport: TCP
  username: dongtaiwang.com
  password: dongtaiwang.com
- name: Node_10_01-10 20:45
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: Node_11_01-10 20:45
  server: 2a14:7583:299d::a
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: Node_12_01-10 20:45
  type: hysteria
  server: 2a14:7584:d097::a
  port: 54177
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- server: 157.254.223.43:27921,28000-29000
  auth: dongtaiwang.com
  bandwidth:
    up: 11 mbps
    down: 55 mbps
  tls:
    sni: apple.com
    insecure: true
  quic:
    initStreamReceiveWindow: 16777216
    maxStreamReceiveWindow: 16777216
    initConnReceiveWindow: 33554432
    maxConnReceiveWindow: 33554432
  socks5:
    listen: 127.0.0.1:1080
  transport:
    udp:
      hopInterval: 30s
  name: Node_13_01-10 20:45
  type: hysteria2
- server: 62.210.124.146:22000
  auth: dongtaiwang.com
  bandwidth:
    up: 11 mbps
    down: 55 mbps
  tls:
    sni: www.microsoft.com
    insecure: true
  quic:
    initStreamReceiveWindow: 16777216
    maxStreamReceiveWindow: 16777216
    initConnReceiveWindow: 33554432
    maxConnReceiveWindow: 33554432
  socks5:
    listen: 127.0.0.1:1080
  transport:
    udp:
      hopInterval: 30s
  name: Node_14_01-10 20:45
  type: hysteria2
- server: '[2a14:7584:d04a::a]:50022'
  auth: dongtaiwang.com
  bandwidth:
    up: 11 mbps
    down: 55 mbps
  tls:
    sni: apple.com
    insecure: true
  quic:
    initStreamReceiveWindow: 16777216
    maxStreamReceiveWindow: 16777216
    initConnReceiveWindow: 33554432
    maxConnReceiveWindow: 33554432
  socks5:
    listen: 127.0.0.1:1080
  transport:
    udp:
      hopInterval: 30s
  name: Node_15_01-10 20:45
  type: hysteria2
- type: vless
  tag: https://github.com/Alvin9999-newpac/fanqiang/wiki
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  packet_encoding: xudp
  server: 157.254.223.44
  server_port: 18959
  flow: ''
  tls:
    enabled: true
    server_name: itunes.apple.com
    utls:
      enabled: true
      fingerprint: chrome
    reality:
      enabled: true
      public_key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
      short_id: d557c6895d014075
  multiplex:
    enabled: true
    protocol: h2mux
    max_connections: 1
    min_streams: 4
    padding: true
    brutal:
      enabled: true
      up_mbps: 50
      down_mbps: 100
  name: Node_16_01-10 20:45
- type: vless
  tag: https://github.com/Alvin9999-newpac/fanqiang/wiki
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  packet_encoding: xudp
  server: 89.144.35.232
  server_port: 15531
  flow: ''
  tls:
    enabled: true
    server_name: itunes.apple.com
    utls:
      enabled: true
      fingerprint: chrome
    reality:
      enabled: true
      public_key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
      short_id: 8346964417a2552b
  multiplex:
    enabled: true
    protocol: h2mux
    max_connections: 1
    min_streams: 4
    padding: true
    brutal:
      enabled: true
      up_mbps: 50
      down_mbps: 100
  name: Node_17_01-10 20:45
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - DIRECT
  - Node_1_01-10 20:45
  - Node_2_01-10 20:45
  - Node_3_01-10 20:45
  - Node_4_01-10 20:45
  - Node_5_01-10 20:45
  - Node_6_01-10 20:45
  - Node_7_01-10 20:45
  - Node_8_01-10 20:45
  - Node_9_01-10 20:45
  - Node_10_01-10 20:45
  - Node_11_01-10 20:45
  - Node_12_01-10 20:45
  - Node_13_01-10 20:45
  - Node_14_01-10 20:45
  - Node_15_01-10 20:45
  - Node_16_01-10 20:45
  - Node_17_01-10 20:45
rules:
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
