ipv6: true
proxies:
- name: ğŸŒ[HYSTERIA2] 02 (01-10 18:07)
  server: 157.254.223.43
  port: 27921
  type: hysteria2
  password: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
- name: ğŸŒ[HYSTERIA2] 03 (01-10 18:07)
  server: 62.210.124.146
  port: 22000
  type: hysteria2
  password: dongtaiwang.com
  sni: www.microsoft.com
  skip-cert-verify: true
- name: ğŸŒ[HYSTERIA2] 04 (01-10 18:07)
  server: 2a14:7584:d04a::a
  port: 50022
  type: hysteria2
  password: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
- name: ğŸŒ[VLESS] 05 (01-10 18:07)
  server: 195.154.200.13
  port: 17401
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  client-fingerprint: chrome
- name: ğŸŒ[VLESS] 06 (01-10 18:07)
  server: '2001'
  port: 17401
  type: vless
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  client-fingerprint: chrome
- name: ğŸŒ[VLESS] 07 (01-10 18:07)
  server: 157.254.223.48
  port: 33990
  type: vless
  uuid: dongtaiwang.com
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
- name: ğŸŒ[TUIC] 08 (01-10 18:07)
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: dongtaiwang.com
  sni: apple.com
  alpn:
  - h3
- name: ğŸŒ[TUIC] 09 (01-10 18:07)
  server: 2a14
  port: 33457
  type: tuic
  uuid: dongtaiwang.com
  sni: apple.com
  alpn:
  - h3
- name: ğŸŒ[VLESS] 10 (01-10 18:07)
  server: 157.254.223.44
  port: 443
  type: vless
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
    short-id: d557c6895d014075
  client-fingerprint: chrome
- name: ğŸŒ[VLESS] 11 (01-10 18:07)
  server: 89.144.35.232
  port: 443
  type: vless
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  tls: true
  servername: itunes.apple.com
  network: tcp
  udp: true
  reality-opts:
    public-key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
    short-id: 8346964417a2552b
  client-fingerprint: chrome
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
  - ğŸŒ[HYSTERIA2] 02 (01-10 18:07)
  - ğŸŒ[HYSTERIA2] 03 (01-10 18:07)
  - ğŸŒ[HYSTERIA2] 04 (01-10 18:07)
  - ğŸŒ[VLESS] 05 (01-10 18:07)
  - ğŸŒ[VLESS] 06 (01-10 18:07)
  - ğŸŒ[VLESS] 07 (01-10 18:07)
  - ğŸŒ[TUIC] 08 (01-10 18:07)
  - ğŸŒ[TUIC] 09 (01-10 18:07)
  - ğŸŒ[VLESS] 10 (01-10 18:07)
  - ğŸŒ[VLESS] 11 (01-10 18:07)
rules:
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
