port: 7890
allow-lan: true
mode: rule
proxies:
- name: '[HYSTERIA] 01 (01-09 21:38)'
  type: hysteria
  server: 89.144.35.30
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[HYSTERIA] 02 (01-09 21:38)'
  type: hysteria
  server: 5.178.101.33
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[VLESS] 01 (01-09 21:38)'
  type: vless
  server: 195.154.200.13
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: '[HYSTERIA] 03 (01-09 21:38)'
  type: hysteria
  server: 2001:bc8:32d7:402::3
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[HYSTERIA] 04 (01-09 21:38)'
  type: hysteria
  server: 2001:bc8:32d7:402::4
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[ANYTLS] 01 (01-09 21:38)'
  type: anytls
  server: 45.221.98.14
  port: 59901
  password: dongtaiwang.com
  client-fingerprint: chrome
  udp: true
  idle-session-check-interval: 30
  idle-session-timeout: 30
  min-idle-session: 0
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: '[VLESS] 02 (01-09 21:38)'
  type: vless
  server: 2001:bc8:32d7:181::2
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: '[VLESS] 03 (01-09 21:38)'
  type: vless
  server: 2001:bc8:32d7:181::3
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: '[MIERU] 01 (01-09 21:38)'
  type: mieru
  server: 157.254.223.48
  port: 33990
  transport: TCP
  username: dongtaiwang.com
  password: dongtaiwang.com
- name: '[TUIC] 01 (01-09 21:38)'
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: '[TUIC] 02 (01-09 21:38)'
  server: 2a14:7583:299d::a
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: '[HYSTERIA] 05 (01-09 21:38)'
  type: hysteria
  server: 2a14:7584:d097::a
  port: 54177
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[HYSTERIA2] 01 (01-09 21:38)'
  type: hysteria2
  server: 157.254.223.43
  port: 27921
  password: dongtaiwang.com
  sni: apple.com
- name: '[HYSTERIA2] 02 (01-09 21:38)'
  type: hysteria2
  server: 62.210.124.146
  port: 22000
  password: dongtaiwang.com
  sni: www.microsoft.com
- name: '[HYSTERIA2] 03 (01-09 21:38)'
  type: hysteria2
  server: '[2a14:7584:d04a::a]'
  port: 50022
  password: dongtaiwang.com
  sni: apple.com
- name: '[VLESS] 04 (01-09 21:38)'
  type: vless
  server: 157.254.223.44
  port: 18959
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  servername: itunes.apple.com
  reality-opts:
    public-key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
    short-id: d557c6895d014075
  client-fingerprint: chrome
- name: '[VLESS] 05 (01-09 21:38)'
  type: vless
  server: 89.144.35.232
  port: 15531
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  servername: itunes.apple.com
  reality-opts:
    public-key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
    short-id: 8346964417a2552b
  client-fingerprint: chrome
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - '[HYSTERIA] 01 (01-09 21:38)'
  - '[HYSTERIA] 02 (01-09 21:38)'
  - '[VLESS] 01 (01-09 21:38)'
  - '[HYSTERIA] 03 (01-09 21:38)'
  - '[HYSTERIA] 04 (01-09 21:38)'
  - '[ANYTLS] 01 (01-09 21:38)'
  - '[VLESS] 02 (01-09 21:38)'
  - '[VLESS] 03 (01-09 21:38)'
  - '[MIERU] 01 (01-09 21:38)'
  - '[TUIC] 01 (01-09 21:38)'
  - '[TUIC] 02 (01-09 21:38)'
  - '[HYSTERIA] 05 (01-09 21:38)'
  - '[HYSTERIA2] 01 (01-09 21:38)'
  - '[HYSTERIA2] 02 (01-09 21:38)'
  - '[HYSTERIA2] 03 (01-09 21:38)'
  - '[VLESS] 04 (01-09 21:38)'
  - '[VLESS] 05 (01-09 21:38)'
  - DIRECT
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - '[HYSTERIA] 01 (01-09 21:38)'
  - '[HYSTERIA] 02 (01-09 21:38)'
  - '[VLESS] 01 (01-09 21:38)'
  - '[HYSTERIA] 03 (01-09 21:38)'
  - '[HYSTERIA] 04 (01-09 21:38)'
  - '[ANYTLS] 01 (01-09 21:38)'
  - '[VLESS] 02 (01-09 21:38)'
  - '[VLESS] 03 (01-09 21:38)'
  - '[MIERU] 01 (01-09 21:38)'
  - '[TUIC] 01 (01-09 21:38)'
  - '[TUIC] 02 (01-09 21:38)'
  - '[HYSTERIA] 05 (01-09 21:38)'
  - '[HYSTERIA2] 01 (01-09 21:38)'
  - '[HYSTERIA2] 02 (01-09 21:38)'
  - '[HYSTERIA2] 03 (01-09 21:38)'
  - '[VLESS] 04 (01-09 21:38)'
  - '[VLESS] 05 (01-09 21:38)'
- name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
  type: select
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DIRECT
- name: ğŸŒ å›½å¤–åª’ä½“
  type: select
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DIRECT
- name: ğŸ¯ å…¨çƒç›´è¿
  type: select
  proxies:
  - DIRECT
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
rules:
- DOMAIN-SUFFIX,telegram.org,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,tg.me,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,netflix.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,youtube.com,ğŸŒ å›½å¤–åª’ä½“
- GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
