port: 7890
allow-lan: true
mode: rule
proxies:
- name: '[HYSTERIA] 01 (01-09 22:20)'
  type: hysteria
  server: 89.144.35.30
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[HYSTERIA] 02 (01-09 22:20)'
  type: hysteria
  server: 5.178.101.33
  port: 23008
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[VLESS] 03 (01-09 22:20)'
  type: vless
  server: 195.154.200.13
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: '[HYSTERIA] 04 (01-09 22:20)'
  type: hysteria
  server: 2001:bc8:32d7:402::3
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[HYSTERIA] 05 (01-09 22:20)'
  type: hysteria
  server: 2001:bc8:32d7:402::4
  port: 20001
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- name: '[ANYTLS] 06 (01-09 22:20)'
  type: anytls
  server: 45.221.98.14
  port: 59901
  password: dongtaiwang.com
  client-fingerprint: chrome
  udp: true
  idle-session-check-interval: 30
  idle-session-timeout: 30
  min-idle-session: 0
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: '[VLESS] 07 (01-09 22:20)'
  type: vless
  server: 2001:bc8:32d7:181::2
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: '[VLESS] 08 (01-09 22:20)'
  type: vless
  server: 2001:bc8:32d7:181::3
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: '[MIERU] 09 (01-09 22:20)'
  type: mieru
  server: 157.254.223.48
  port: 33990
  transport: TCP
  username: dongtaiwang.com
  password: dongtaiwang.com
- name: '[TUIC] 10 (01-09 22:20)'
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: '[TUIC] 11 (01-09 22:20)'
  server: 2a14:7583:299d::a
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: '[HYSTERIA] 12 (01-09 22:20)'
  type: hysteria
  server: 2a14:7584:d097::a
  port: 54177
  auth-str: dongtaiwang.com
  sni: apple.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
- type: hysteria2
  server: 157.254.223.43
  port: 27921
  password: dongtaiwang.com
  sni: apple.com
  name: '[HYSTERIA2] 13 (01-09 22:20)'
- type: hysteria2
  server: 62.210.124.146
  port: 22000
  password: dongtaiwang.com
  sni: www.microsoft.com
  name: '[HYSTERIA2] 14 (01-09 22:20)'
- type: hysteria2
  server: '[2a14:7584:d04a::a]'
  port: 50022
  password: dongtaiwang.com
  sni: apple.com
  name: '[HYSTERIA2] 15 (01-09 22:20)'
- name: '[VLESS] 16 (01-09 22:20)'
  type: vless
  server: 157.254.223.44
  port: 18959
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  network: tcp
  servername: itunes.apple.com
  reality-opts:
    public-key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
    short-id: d557c6895d014075
  ws-opts: null
- name: '[VLESS] 17 (01-09 22:20)'
  type: vless
  server: 89.144.35.232
  port: 15531
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  network: tcp
  servername: itunes.apple.com
  reality-opts:
    public-key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
    short-id: 8346964417a2552b
  ws-opts: null
- name: '[VLESS] 18 (01-09 22:20)'
  type: vless
  server: 62.210.127.177
  port: 60011
  uuid: a1f699e4-d7b7-4cdc-8414-1105e08fe4c5
  network: xhttp
  servername: www.pixiv.co.jp
  reality-opts:
    public-key: BTCE_8R4FJ7wf9mR7PkONJyeihtHqi_TptjC20eMhic
    short-id: ea22dff3025e4ff8
  ws-opts:
    path: /github.com/Alvin9999
- name: '[VLESS] 19 (01-09 22:20)'
  type: vless
  server: fan3.394615.xyz
  port: 34500
  uuid: 8b66e552-e89d-4c4f-bb5a-e3d37bf151b8
  network: xhttp
  servername: www.lovelive-anime.jp
  reality-opts:
    public-key: Yg6kOijRv1IbFcwhY0WmwJ8KW7YTtux4QlQhekEzNEQ
    short-id: 3a1381d1b2cc9e19
  ws-opts:
    path: /ZTwhzkrWeLnk5ARp8SsoVlVMGn6cSDq8CElbAniRQ9dMR
- name: '[VLESS] 20 (01-09 22:20)'
  type: vless
  server: 89.144.35.230
  port: 54582
  uuid: 5cfc52bc-e701-4160-89df-930a0c040576
  network: xhttp
  servername: apple.com
  reality-opts:
    public-key: kfw5DgkyKiovC3dzb-o2PUYnZPnbYvbx2IwERUv9czY
    short-id: 225e2cc8
  ws-opts:
    path: 5cfc52bc-e701-4160-89df-930a0c040576-xh
- name: '[VLESS] 21 (01-09 22:20)'
  type: vless
  server: 2a14:7584:d097::a
  port: 11330
  uuid: 53d74aab-6471-4c1b-ace7-fac837d1bfbd
  network: xhttp
  servername: toarumajutsunoindex.fandom.com
  reality-opts:
    public-key: 3HaD5Ztk3X4gi3aJLVesV6KSJTW2YGG-hvGD3ZumJkE
    short-id: fa789b2f5ff56959
  ws-opts:
    path: /alvin9999.com
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - '[HYSTERIA] 01 (01-09 22:20)'
  - '[HYSTERIA] 02 (01-09 22:20)'
  - '[VLESS] 03 (01-09 22:20)'
  - '[HYSTERIA] 04 (01-09 22:20)'
  - '[HYSTERIA] 05 (01-09 22:20)'
  - '[ANYTLS] 06 (01-09 22:20)'
  - '[VLESS] 07 (01-09 22:20)'
  - '[VLESS] 08 (01-09 22:20)'
  - '[MIERU] 09 (01-09 22:20)'
  - '[TUIC] 10 (01-09 22:20)'
  - '[TUIC] 11 (01-09 22:20)'
  - '[HYSTERIA] 12 (01-09 22:20)'
  - '[HYSTERIA2] 13 (01-09 22:20)'
  - '[HYSTERIA2] 14 (01-09 22:20)'
  - '[HYSTERIA2] 15 (01-09 22:20)'
  - '[VLESS] 16 (01-09 22:20)'
  - '[VLESS] 17 (01-09 22:20)'
  - '[VLESS] 18 (01-09 22:20)'
  - '[VLESS] 19 (01-09 22:20)'
  - '[VLESS] 20 (01-09 22:20)'
  - '[VLESS] 21 (01-09 22:20)'
  - DIRECT
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - '[HYSTERIA] 01 (01-09 22:20)'
  - '[HYSTERIA] 02 (01-09 22:20)'
  - '[VLESS] 03 (01-09 22:20)'
  - '[HYSTERIA] 04 (01-09 22:20)'
  - '[HYSTERIA] 05 (01-09 22:20)'
  - '[ANYTLS] 06 (01-09 22:20)'
  - '[VLESS] 07 (01-09 22:20)'
  - '[VLESS] 08 (01-09 22:20)'
  - '[MIERU] 09 (01-09 22:20)'
  - '[TUIC] 10 (01-09 22:20)'
  - '[TUIC] 11 (01-09 22:20)'
  - '[HYSTERIA] 12 (01-09 22:20)'
  - '[HYSTERIA2] 13 (01-09 22:20)'
  - '[HYSTERIA2] 14 (01-09 22:20)'
  - '[HYSTERIA2] 15 (01-09 22:20)'
  - '[VLESS] 16 (01-09 22:20)'
  - '[VLESS] 17 (01-09 22:20)'
  - '[VLESS] 18 (01-09 22:20)'
  - '[VLESS] 19 (01-09 22:20)'
  - '[VLESS] 20 (01-09 22:20)'
  - '[VLESS] 21 (01-09 22:20)'
- name: üéØ ÂÖ®ÁêÉÁõ¥Ëøû
  type: select
  proxies:
  - DIRECT
  - üöÄ ËäÇÁÇπÈÄâÊã©
rules:
- GEOIP,CN,üéØ ÂÖ®ÁêÉÁõ¥Ëøû
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
