ipv6: true
allow-lan: true
mode: rule
proxies:
- name: ğŸŒ_01_01-10 21:04
  type: vless
  server: 195.154.200.13
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: ğŸŒ_02_01-10 21:04
  type: anytls
  server: 45.221.98.14
  port: 59901
  password: dongtaiwang.com
  client-fingerprint: chrome
  udp: true
  idle-session-check-interval: 30
  idle-session-timeout: 30
  min-idle-session: 0
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: ğŸŒ_03_01-10 21:04
  type: vless
  server: 2001:bc8:32d7:181::2
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: ğŸŒ_04_01-10 21:04
  type: vless
  server: 2001:bc8:32d7:181::3
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  network: tcp
  udp: true
  tls: true
  flow: null
  servername: itunes.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
      enabled: true
      up: 50
      down: 100
- name: ğŸŒ_05_01-10 21:04
  type: mieru
  server: 157.254.223.48
  port: 33990
  transport: TCP
  username: dongtaiwang.com
  password: dongtaiwang.com
- name: ğŸŒ_06_01-10 21:04
  server: 89.144.35.231
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- name: ğŸŒ_07_01-10 21:04
  server: 2a14:7583:299d::a
  port: 33457
  type: tuic
  uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
  password: dongtaiwang.com
  alpn:
  - h3
  sni: apple.com
  skip-cert-verify: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
- server: 157.254.223.43:27921,28000-29000
  auth: dongtaiwang.com
  bandwidth:
    up: 11 mbps
    down: 55 mbps
  tls:
    sni: apple.com
    insecure: true
  quic:
    initStreamReceiveWindow: 16777216
    maxStreamReceiveWindow: 16777216
    initConnReceiveWindow: 33554432
    maxConnReceiveWindow: 33554432
  socks5:
    listen: 127.0.0.1:1080
  transport:
    udp:
      hopInterval: 30s
  type: hysteria2
  name: ğŸŒ_08_01-10 21:04
- server: 62.210.124.146:22000
  auth: dongtaiwang.com
  bandwidth:
    up: 11 mbps
    down: 55 mbps
  tls:
    sni: www.microsoft.com
    insecure: true
  quic:
    initStreamReceiveWindow: 16777216
    maxStreamReceiveWindow: 16777216
    initConnReceiveWindow: 33554432
    maxConnReceiveWindow: 33554432
  socks5:
    listen: 127.0.0.1:1080
  transport:
    udp:
      hopInterval: 30s
  type: hysteria2
  name: ğŸŒ_09_01-10 21:04
- server: '[2a14:7584:d04a::a]:50022'
  auth: dongtaiwang.com
  bandwidth:
    up: 11 mbps
    down: 55 mbps
  tls:
    sni: apple.com
    insecure: true
  quic:
    initStreamReceiveWindow: 16777216
    maxStreamReceiveWindow: 16777216
    initConnReceiveWindow: 33554432
    maxConnReceiveWindow: 33554432
  socks5:
    listen: 127.0.0.1:1080
  transport:
    udp:
      hopInterval: 30s
  type: hysteria2
  name: ğŸŒ_10_01-10 21:04
- type: vless
  tag: https://github.com/Alvin9999-newpac/fanqiang/wiki
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  packet_encoding: xudp
  server: 157.254.223.44
  server_port: 18959
  flow: ''
  tls:
    enabled: true
    server_name: itunes.apple.com
    utls:
      enabled: true
      fingerprint: chrome
    reality:
      enabled: true
      public_key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
      short_id: d557c6895d014075
  multiplex:
    enabled: true
    protocol: h2mux
    max_connections: 1
    min_streams: 4
    padding: true
    brutal:
      enabled: true
      up_mbps: 50
      down_mbps: 100
  name: ğŸŒ_11_01-10 21:04
- type: vless
  tag: https://github.com/Alvin9999-newpac/fanqiang/wiki
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  packet_encoding: xudp
  server: 89.144.35.232
  server_port: 15531
  flow: ''
  tls:
    enabled: true
    server_name: itunes.apple.com
    utls:
      enabled: true
      fingerprint: chrome
    reality:
      enabled: true
      public_key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
      short_id: 8346964417a2552b
  multiplex:
    enabled: true
    protocol: h2mux
    max_connections: 1
    min_streams: 4
    padding: true
    brutal:
      enabled: true
      up_mbps: 50
      down_mbps: 100
  name: ğŸŒ_12_01-10 21:04
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - DIRECT
  - ğŸŒ_01_01-10 21:04
  - ğŸŒ_02_01-10 21:04
  - ğŸŒ_03_01-10 21:04
  - ğŸŒ_04_01-10 21:04
  - ğŸŒ_05_01-10 21:04
  - ğŸŒ_06_01-10 21:04
  - ğŸŒ_07_01-10 21:04
  - ğŸŒ_08_01-10 21:04
  - ğŸŒ_09_01-10 21:04
  - ğŸŒ_10_01-10 21:04
  - ğŸŒ_11_01-10 21:04
  - ğŸŒ_12_01-10 21:04
rules:
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
