port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
  - name: https://github.com/Alvin9999-newpac/fanqiang/wiki
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
  - name: dongtaiwang.com_0
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
  - name: ğŸŒ å›½å¤–åª’ä½“
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - name: ğŸ è‹¹æœæœåŠ¡
  - name: dongtaiwang.com_1
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: dongtaiwang.com_4
  - name: dongtaiwang.com_2
  - name: dongtaiwang.com_3
  - name: ğŸ¯ å…¨çƒç›´è¿