proxies:
- name: ğŸŒ_01_01-10 21:51
  type: vless
  server: 195.154.200.13
  port: 17401
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  cipher: auto
  tls: true
  sni: itunes.apple.com
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  network: tcp
- name: ğŸŒ_02_01-10 21:51
  type: vless
  server: 45.221.98.14
  port: 59901
  uuid: dongtaiwang.com
  cipher: auto
  tls: false
- name: ğŸŒ_03_01-10 21:51
  type: vless
  server: '2001:bc8:32d7:181:'
  port: 2
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  cipher: auto
  tls: true
  sni: itunes.apple.com
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  network: tcp
- name: ğŸŒ_04_01-10 21:51
  type: vless
  server: '2001:bc8:32d7:181:'
  port: 3
  uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
  cipher: auto
  tls: true
  sni: itunes.apple.com
  reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
  network: tcp
- name: ğŸŒ_05_01-10 21:51
  type: mieru
  server: 157.254.223.48
  port: 33990
  uuid: dongtaiwang.com
  cipher: auto
  tls: false
- name: ğŸŒ_05_01-10 21:51
  type: tuic
  server: 89.144.35.231
  port: 33457
  uuid: dongtaiwang.com
  cipher: auto
  tls: true
  sni: apple.com
- name: ğŸŒ_06_01-10 21:51
  type: tuic
  server: '2a14:7583:299d:'
  port: 33457
  uuid: dongtaiwang.com
  cipher: auto
  tls: true
  sni: apple.com
- name: ğŸŒ_07_01-10 21:51
  type: vless
  server: 157.254.223.43
  port: 27921
  uuid: dongtaiwang.com
  cipher: auto
  tls: true
  sni: apple.com
- name: ğŸŒ_08_01-10 21:51
  type: vless
  server: 62.210.124.146
  port: 22000
  uuid: dongtaiwang.com
  cipher: auto
  tls: true
  sni: www.microsoft.com
- name: ğŸŒ_09_01-10 21:51
  type: vless
  server: 2a14:7584:d04a::a
  port: 50022
  uuid: dongtaiwang.com
  cipher: auto
  tls: true
  sni: apple.com
- name: ğŸŒ_10_01-10 21:51
  type: vless
  server: 157.254.223.44
  port: 18959
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  cipher: auto
  tls: true
  reality-opts:
    public-key: -hwVEdgFkvjku8ESuDoAA7id5yGGv_zXBvBW_RdhmHA
    short-id: d557c6895d014075
- name: ğŸŒ_11_01-10 21:51
  type: vless
  server: 89.144.35.232
  port: 15531
  uuid: d3fd3b3c-f8d4-4894-b91e-5a6a53923a95
  cipher: auto
  tls: true
  reality-opts:
    public-key: o4gXQf1n5YOoLo6OnyHykodK1ZShHvDqu1FgxNHe6n8
    short-id: 8346964417a2552b
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - DIRECT
  - ğŸŒ_01_01-10 21:51
  - ğŸŒ_02_01-10 21:51
  - ğŸŒ_03_01-10 21:51
  - ğŸŒ_04_01-10 21:51
  - ğŸŒ_05_01-10 21:51
  - ğŸŒ_05_01-10 21:51
  - ğŸŒ_06_01-10 21:51
  - ğŸŒ_07_01-10 21:51
  - ğŸŒ_08_01-10 21:51
  - ğŸŒ_09_01-10 21:51
  - ğŸŒ_10_01-10 21:51
  - ğŸŒ_11_01-10 21:51
rules:
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
