port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
  - name: "Node_01"
    https://github.com/Alvin9999-newpac/fanqiang/wiki
    type: hysteria
    server: 89.144.35.30
    port: 23008
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn:
    - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_02"
    dongtaiwang.com_1
    type: hysteria
    server: 5.178.101.33
    port: 23008
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn:
    - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_03"
    https://github.com/Alvin9999-newpac/fanqiang/wiki
    type: vless
    server: 195.154.200.13
    port: 17401
    uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
    network: tcp
    udp: true
    tls: true
    flow:
    client-fingerprint: chrome
    reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
    smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
    enabled: true
    up: 50
    down: 100
  - name: "Node_04"
    dongtaiwang.com_3
    type: hysteria
    server: 2001:bc8:32d7:402::3
    port: 20001
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn:
    - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_05"
    dongtaiwang.com_4
    type: hysteria
    server: 2001:bc8:32d7:402::4
    port: 20001
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn:
    - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "Node_06"
    dongtaiwang.com_0
    type: anytls
    server: 45.221.98.14
    port: 59901
    password: dongtaiwang.com
    client-fingerprint: chrome
    udp: true
    idle-session-check-interval: 30
    idle-session-timeout: 30
    min-idle-session: 0
    alpn:
    - h2
    - http/1.1
    skip-cert-verify: true
  - name: "Node_07"
    dongtaiwang.com_1
    type: vless
    server: 2001:bc8:32d7:181::2
    port: 17401
    uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
    network: tcp
    udp: true
    tls: true
    flow:
    client-fingerprint: chrome
    reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
    smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
    enabled: true
    up: 50
    down: 100
  - name: "Node_08"
    dongtaiwang.com_2
    type: vless
    server: 2001:bc8:32d7:181::3
    port: 17401
    uuid: add14a5b-f648-4423-8a1f-8b8f54c0daef
    network: tcp
    udp: true
    tls: true
    flow:
    client-fingerprint: chrome
    reality-opts:
    public-key: IXcXrT_Y0ATTZlGOhPnSmKo-cuGr4yMKV9Rz4-nA3yU
    short-id: 8ef4455ba637425b
    smux:
    enabled: true
    protocol: h2mux
    max-connections: 1
    min-streams: 4
    padding: true
    brutal-opts:
    enabled: true
    up: 50
    down: 100
  - name: "Node_09"
    dongtaiwang.com_0
    type: mieru
    server: 157.254.223.48
    port: 33990
    transport: TCP
    password: dongtaiwang.com
  - name: "Node_10"
    https://github.com/Alvin9999-newpac/fanqiang/wiki
    server: 89.144.35.231
    port: 33457
    type: tuic
    uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
    password: dongtaiwang.com
    alpn: [h3]
    sni: apple.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
  - name: "Node_11"
    dongtaiwang.com_1
    server: 2a14:7583:299d::a
    port: 33457
    type: tuic
    uuid: 66d37a65-7f6f-4e7c-a0f6-163bd917756a
    password: dongtaiwang.com
    alpn: [h3]
    sni: apple.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
  - name: "Node_12"
    https://github.com/Alvin9999-newpac/fanqiang/wiki
    type: hysteria
    server: 2a14:7584:d097::a
    port: 54177
    auth-str: dongtaiwang.com
    sni: apple.com
    skip-cert-verify: true
    alpn:
    - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"

proxy-groups:
  - name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - "Node_01"
      - "Node_02"
      - "Node_03"
      - "Node_04"
      - "Node_05"
      - "Node_06"
      - "Node_07"
      - "Node_08"
      - "Node_09"
      - "Node_10"
      - "Node_11"
      - "Node_12"
      - DIRECT

rules:
  - MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©